ignoreGeneratedHeader = true
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.atomic]
[rule.bare-return]
[rule.call-to-gc]
[rule.confusing-naming]
[rule.confusing-results]
[rule.constant-logical-expr]
[rule.context-keys-type]
[rule.deep-exit]
[rule.defer]
    arguments=[["call-chain","loop","method-call","recover","return"]]
[rule.dot-imports]
[rule.duplicated-imports]
[rule.empty-block]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
[rule.function-result-limit]
    arguments=[5]
[rule.get-return]
[rule.identical-branches]
[rule.increment-decrement]
[rule.indent-error-flow]
[rule.import-shadowing]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.nested-structs]
[rule.range]
[rule.range-val-in-closure]
[rule.range-val-address]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.string-of-int]
[rule.struct-tag]
[rule.superfluous-else]
[rule.time-naming]
[rule.var-declaration]
[rule.unconditional-recursion]
[rule.unexported-naming]
[rule.unexported-return]
[rule.unreachable-code]
[rule.useless-break]
[rule.waitgroup-by-value]

# POSSIBLE
# [rule.argument-limit]
#     arguments = [5]
# [rule.cyclomatic]
#     arguments=[3]
# [rule.cognitive-complexity]
#     arguments=[10]

[rule.bool-literal-in-expr]
